src/app/elasticsearch/routes.py
"""Module from elasticsearch subpackage with routes for Elasticsearch features."""

__docformat__ = "google"

import string

import flask
from flask import jsonify, render_template, request, url_for, Blueprint
from elasticsearch import ApiError, TransportError
from elastic_transport import ObjectApiResponse

from .. import es
from ..graphs.utils import read_logs
from .utils import perform_elasticsearch_query

elasticsearch = Blueprint("elasticsearch", __name__)


@elasticsearch.route("/upload")
def upload_documents() -> dict:
    """Upload documents to an Elasticsearch index.

    Returns:
        Empty dictionary.
    """
    _, df = read_logs()

    id = 1
    for day in df["day"].unique():

        doc_in_a_day = df[df["day"] == day].fillna(value=0).to_dict("records")
        for doc in doc_in_a_day:
            # print(id)
            # print(doc)
            try:
                resp = es.index(index="logs-index", id=id, document=doc)
            except ApiError as err:
                print("ApiError")
                print(err.meta.status)
                print(err.meta.headers)
                print(err.body)
                continue
            except TransportError as err:
                print("TransportError")
                print(err)
                continue

            if resp["result"] != "created" or resp["result"] != "updated":
                print(resp["result"])

            id += 1

    return {}


@elasticsearch.route("/search", methods=["POST"])
def search():
    """Return the search results page.

    Returns:
        Rendered template with the search results page.
    """
    hits = search_helper()
    return render_template("query_results.html", hits=hits)


@elasticsearch.route("/api/search", methods=["POST", "GET"])
def api_search() -> flask.Response:
    """Return the search results as a JSON object.

    Query parameters:
        - **query**: query string.\n
        - **day**: 1 if day is to be included in the search results, 0 otherwise.\n
        - **mime_types**: 1 if mime_types is to be included in the search results, 0 otherwise.\n
        - **mime_types_count**: 1 if mime_types_count is to be included in the search results, 0 otherwise.\n
        - **status_codes**: 1 if status_codes is to be included in the search results, 0 otherwise.\n
        - **status_codes_count**: 1 if status_codes_count is to be included in the search results, 0 otherwise.

    Returns:
        JSON object with the search results.

    Examples:
        >>> curl -X GET "http://localhost:5000/api/search?query=39&day=1"
    """
    hits = search_helper()
    for hit in hits:
        if hit["_source"]["mime_types"] != 0.0:
            hit["_source"]["mime_types_count"] = int(hit["_source"]["mime_types_count"])
        if hit["_source"]["status_codes"] != 0.0:
            hit["_source"]["status_codes"] = int(hit["_source"]["status_codes"])
            hit["_source"]["status_codes_count"] = int(
                hit["_source"]["status_codes_count"]
            )
    return jsonify(hits)


@elasticsearch.route("/api/search/<int:id>")
def api_search_by(id: int) -> ObjectApiResponse:
    """Find a document by its ID.

    Args:
        id: document ID

    Returns:
        JSON object with the document.

    Examples:
        >>> curl -X GET "http://localhost:5000/api/search/164"
    """

    try:
        resp = es.get(index="logs-index", id=id)

    except ApiError as err:
        print(err.meta.status)
        print(err.meta.headers)
        print(err.body)
        return jsonify({})

    return resp["_source"]


@elasticsearch.route("/api/delete/<int:id>")
def api_delete_by(id: int) -> flask.Response:
    """Delete a document by its ID.

    Args:
        id: document ID

    Returns:
        Empty JSON object.

    Examples:
        >>> curl -X GET "http://localhost:5000/api/delete/164"
    """
    es.delete(index="logs-index", id=id)
    return jsonify({})


def search_helper():
    """Return the search results based on the request method and query parameters.

    Returns:
        Search results as a list of dictionaries or empty dict or empty list.
    """
    # Get the search query from the form or query parameters, depending on the request method
    if request.method == "POST":

        search_query = request.form["query"]
        fields = []
        if "day" in request.form:
            fields.append("day")
        if "mime_types" in request.form:
            fields.append("mime_types")
        if "mime_types_count" in request.form:
            fields.append("mime_types_count")
        if "status_codes" in request.form:
            fields.append("status_codes")
        if "status_codes_count" in request.form:
            fields.append("status_codes_count")
    elif request.method == "GET":

        search_query = request.args.get("query")
        fields = []
        if "day" in request.args:
            fields.append("day")
        if "mime_types" in request.args:
            fields.append("mime_types")
        if "mime_types_count" in request.args:
            fields.append("mime_types_count")
        if "status_codes" in request.args:
            fields.append("status_codes")
        if "status_codes_count" in request.args:
            fields.append("status_codes_count")

    if search_query is None:
        return {}

    if search_query in string.whitespace:
        return []

    # Call a separate function to perform the Elasticsearch query
    resp = perform_elasticsearch_query(search_query, fields)

    return resp["hits"]["hits"]

src/app/main/routes.py
"""Module from main subpackage with routes for common pages"""

__docformat__ = "google"

from flask import render_template, url_for, Blueprint


main = Blueprint("main", __name__)


@main.route("/")
def index():
    """Return the index page.

    Returns:
        Rendered template with the about page.
    """
    return render_template("about.html", title="LambdaTest")


@main.route("/about")
def about():
    """Return the about page.

    Returns:
        Rendered template with the about page.
    """
    return render_template("about.html", title="About")

src/app/templates/about.html
{% extends "layout.html" %}
{% block content %}

<div class="pb-5">
    <h1>Assignment</h1>
    <hr>
    <h2>Test Logs Visualization with Graphs</h2>
    <hr>
    <p>As a company, I run ~2 Million Selenium test Network logs a day on cloud. Build an ability to graphically visualize the logs using a low end resource cloud architecture framework. This code should be able to package and run on self-hosted machines or on cloud with proxy settings and public APIs for subscribed customers.<p>

    <h2>Task instructions</h2>
    <p>The following are the prerequisites for the task:</p>

    <ul>
    <li>Setup Selenium on your local machine</li>
    <li>Write the script for opening the URL (https://www.lambdatest.com/)</li>
    <li>Click on each header navigation items</li>
    <li>Store the network logs generated on the browser to your local machine.</li>
    <li>Repeat the process for more than 100 tests</li>
    <li>The following are the requirements for the task: Use a lightweight graph library which can render a time series of 365 days on the x-axis and y-axis should be the following:</li>
    </ul>

    Total count of logs
    <ul>
    <li>Logs count/average stacked by log type (mime-type)</li>
    <li>Logs count/average stacked by log level (Status Codes)</li>
    <li>Logs should be able to filter on the UI by any available key-value.</li>
    <li>Logs should be searchable with a keyword using an API to fetch the results.</li>
    </ul>

    <p>You can use the recommended tech stack for developing this fullstack application:</p>

    <ul>
    <li>ElasticSearch or any text search engine.</li>
    <li>ReactJS</li>
    <li>Go lang (or) Python for server</li>
    </ul>
</div>


{% endblock content %}

src/app/templates/dashboard.html
{% extends "layout.html" %}
{% block content %}
<div class="card">
  <div class="card-body">
  <h5 class="card-title">Total count of logs</h5>
  <p class="card-text">{{ total_count_of_logs }}</p>
  </div>
</div>

<form method="GET" action="{{ url_for('graphs.dashboard_day', day=0) }}">
  <div class="input-group">
    <label class="input-group-text" for="day-select">Select a day:</label>
    <select class="form-select" id="day-select" name="day">
      {% for d in range(1, 366) %}
        <option value="{{ d }}" {% if d == current_day %}selected{% endif %}>{{ d }}</option>
      {% endfor %}
    </select>
    <button class="btn btn-primary" type="submit">Go</button>
  </div>
</form>


{{ plot_html|safe }}

{% endblock content %}

src/app/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</head>

<body>
  <nav class="navbar navbar-expand-lg bg-light py-4 px-4 mb-4">
    <div class="container-fluid">
      <a class="navbar-brand" href="{{ url_for('main.index') }}">GitHub Octernship Assignment</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.about') }}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('graphs.dashboard') }}">Dashboard</a>
          </li>
        </ul>
        
        <form class="d-flex" role="search" action="{{ url_for('elasticsearch.search') }}" method="POST">
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="checkbox" name="day" id="day" value="1">
                <label class="form-check-label" for="day">Day</label>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="checkbox" name="mime_types" id="mime_types" value="1">
                <label class="form-check-label" for="mime_types">MIME Types</label>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="checkbox" name="mime_types_count" id="mime_types_count" value="1">
                <label class="form-check-label" for="mime_types_count">MIME Types Count</label>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="checkbox" name="status_codes" id="status_codes" value="1">
                <label class="form-check-label" for="status_codes">Status Codes</label>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="checkbox" name="status_codes_count" id="status_codes_count" value="1">
                <label class="form-check-label" for="status_codes_count">Status Codes Count</label>
            </div>
            <div class="input-group">
                <input class="form-control" type="search" placeholder="Search" aria-label="Search" name="query">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </div>
        </form>


      </div>
    </div>
  </nav>

  <div class="container">
    <!-- Main content goes here -->
    {% block content %}{% endblock content %}

  </div>

  <!-- Footer -->
  <footer class="fixed-bottom pt-2 px-4 text-white" style="background-color: #777;">
    <p>Copyright © 2023 OscarSantosMu</p>
  </footer>

</body>

</html>

src/app/templates/query_results.html
{% extends "layout.html" %}
{% block content %}

<h1>Search Results</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Day</th>
      <th>Mime Types</th>
      <th>Mime Types Count</th>
      <th>Status Codes</th>
      <th>Status Codes Count</th>
    </tr>
  </thead>
  <tbody>
    {% for hit in hits %}
    <tr>
      <td>{{ hit["_id"] }}</td>
      <td>{{ hit["_source"]["day"] }}</td>
      <td>
        {% if hit["_source"]["mime_types"] != 0.0 %}
            {{ hit["_source"]["mime_types"] }}
        {% endif %}
      </td>
      <td>
        {% if hit["_source"]["mime_types_count"] != 0.0 %}
            {{ hit["_source"]["mime_types_count"]|int }}
        {% endif %}
      </td>
      <td>
        {% if hit["_source"]["status_codes"] != 0.0 %}
            {{ hit["_source"]["status_codes"]|int }}
        {% endif %}
      </td>
      <td>
        {% if hit["_source"]["status_codes_count"] != 0.0 %}
            {{ hit["_source"]["status_codes_count"]|int }}
        {% endif %}
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>


{% endblock content %}